### ISSUE TITLE
Benign/Malignant labels in original InBreast dataset

### ISSUE THREAD

**Issue by akbwaj** [wentaozhu/deep-mil-for-whole-mammogram-classification#17]
I have received the original InBreast dataset from the author, but can not find any description of Benign/Malignant labels in there. I do, however notice a label.txt file that you are using to generate labels. May I know where is this file generated from and what do the labels mean?

**Comment by wentaozhu** [comment]
https://github.com/wentaozhu/deep-mil-for-whole-mammogram-classification/blob/master/inbreast.py

readlabel() function is the one to turn the label to benign and malignant. 

Generally, if the score is bigger than 3, it is malignant. Otherwise it is benign. You can find it from the paper.

Deep Multi-instance Networks with Sparse Label Assignment for Whole Mammogram Classification. MICCAI 2017.

**Comment by akbwaj** [comment]
Thank you for the information. I am actually looking for the Benign/Malignant findings after the biopsy. These are not provided anymore as part of the dataset. Thanks again!

**Comment by yawwG** [comment]
Actually, we can find the biopsy result from the medical report, then pick the corresponding label.
